In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [2]:
df = pd.read_csv("focus.csv")
df.columns = df.columns.str.strip()
df.head()


In [3]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 18 columns):
 #   Column                                                                                Non-Null Count  Dtype 
---  ------                                                                                --------------  ----- 
 0   Timestamp                                                                             83 non-null     object
 1   Email Address                                                                         83 non-null     object
 2   Age Group                                                                             83 non-null     object
 3   Gender                                                                                83 non-null     object
 4   Role                                                                                  83 non-null     object
 5   1.Average daily screen time (in hours)?                                               83 non-n

In [4]:
df.describe(include='all')


In [5]:
plt.figure()
df['Age Group'].value_counts().plot(kind='bar')
plt.title('Age Group Distribution')
plt.xlabel('Age Group')
plt.ylabel('Count')
plt.show()


In [6]:
plt.figure()
df['Gender'].value_counts().plot(kind='bar')
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()


In [7]:
plt.figure()
df['Role'].value_counts().plot(kind='bar')
plt.title('Role Distribution')
plt.xlabel('Role')
plt.ylabel('Count')
plt.show()


In [8]:
plt.figure()
df['14.Rate your overall concentration ability'].plot(kind='hist')
plt.title('Concentration Ability Distribution')
plt.xlabel('Concentration Level')
plt.show()


In [9]:
df.drop(['Timestamp', 'Email Address'], axis=1, inplace=True)
df.head()


In [10]:
le = LabelEncoder()

for col in df.columns:
    df[col] = le.fit_transform(df[col])

df.head()


In [11]:
X = df.drop('14.Rate your overall concentration ability', axis=1)
y = df['14.Rate your overall concentration ability']


In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [13]:
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)


In [14]:
y_pred = model.predict(X_test)


In [15]:
print("Accuracy:", accuracy_score(y_test, y_pred))


Accuracy: 0.5294117647058824


In [16]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.50      0.25      0.33         4
           2       0.50      1.00      0.67         5
           3       0.60      0.50      0.55         6

    accuracy                           0.53        17
   macro avg       0.40      0.44      0.39        17
weighted avg       0.48      0.53      0.47        17



C:\Users\prath\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\prath\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\prath\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [17]:
print(confusion_matrix(y_test, y_pred))


[[0 1 0 1]
 [0 1 2 1]
 [0 0 5 0]
 [0 0 3 3]]


In [18]:
importance = model.feature_importances_
features = X.columns

plt.figure(figsize=(10,6))
plt.barh(features, importance)
plt.title("Feature Importance (Factors affecting concentration)")
plt.show()


In [19]:
sample = X.iloc[[0]]   # keep it as DataFrame, not values
prediction = model.predict(sample)

target_le = LabelEncoder()
target_le.fit(df['14.Rate your overall concentration ability'])

decoded = target_le.inverse_transform(prediction)

print("Predicted Concentration Level (1-5):", decoded[0])


Predicted Concentration Level (1-5): 1
